### ISSUE TITLE
Suggesting more great projects

### ISSUE THREAD

**Issue by bpetit** [github/GreenSoftwareDirectory#2]
Thanks for your work and the visibility you enable to the projects listed.

Open-source projects I would have loved to see in and/or higher in this list : 

- [BoaviztAPI](https://github.com/Boavizta/boaviztapi) from Boavizta (having embodied emissions and up to 16 environemental impacts for devices, seems cool right ?! plus it's as in the core of many projects to go beyong energy/co2 usage phase impacts)
- [PowerJoular](https://github.com/joular/powerjoular) from Adel Nourredine & UPPA
- [Ecobenchmark](https://github.com/Boavizta/ecobenchmark-applicationweb-backend) from Boavizta
- [PowerAPI](https://github.com/powerapi-ng/powerapi) from Romain Rouvoy & INRIA
- [EcoCode](https://github.com/green-code-initiative/ecoCode) from the green-code-initiative

- and so much more... that [Boavizta](https://github.com/Boavizta) has started to extensively track and classify in an open-data database, coming soon !

**Comment by abbitude** [comment]
Hi there! 👋 

Thank you so much for opening an issue and for your interest in contributing to GitHub's Green Software Directory.

To contribute a project (or multiple projects) that is actively being used/developed and can be used by others, please follow these steps to create a pull request:

- Create a fork of this project.
- Create a new branch
- Add your project to a relevant category in the following format: [Project Name](Project URL) - A sentence that describes your project.
- Create a pull request and wait for it to be reviewed and merged.

For more detailed instructions on creating pull requests, check out the official [GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Thank you again for your contribution!
