### ISSUE TITLE
Suggest to add Cardamon

### ISSUE THREAD

**Issue by anewmandev** [github/GreenSoftwareDirectory#4]
Hi there. Great repo for the Green Software community. Please can we add Cardamon?

- Cardamon back-end: https://github.com/Root-Branch/cardamon
- Cardamon front-end: https://web.cardamon.io
- Website: https://cardamon.io

Cardamon measures front end websites and software processes on the back end. The aim is to support end to end measurements compatible with SCI spec.

**Comment by anewmandev** [comment]
created PR #5 for review

**Comment by abbitude** [comment]
Hi there! 👋 

Thank you so much for opening an issue and for your interest in contributing to GitHub's Green Software Directory.

To contribute a project (or multiple projects) that is actively being used/developed and can be used by others, please follow these steps to create a pull request:

- Create a fork of this project.
- Create a new branch
- Add your project to a relevant category in the following format: [Project Name](Project URL) - A sentence that describes your project.
- Create a pull request and wait for it to be reviewed and merged.

For more detailed instructions on creating pull requests, check out the official [GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Thank you again for your contribution!
